<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>COR 1 - Copy</name>
   <tag></tag>
   <elementGuidId>435124bf-a988-4dd2-b886-c7ff2c803377</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'CO01' or . = 'CO01')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'COR 1' or . = 'COR 1')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-150-option-6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;COR 1&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0507fc11-aa2a-46ef-947c-58d8394aeb56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Select2__option Select2__option--is-focused css-d7l1ni-option</value>
      <webElementGuid>f7616823-690f-4bac-b998-12dd8f9a2958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>24e40f14-15f4-4304-8682-9bd8c7df0f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-150-option-6</value>
      <webElementGuid>6f4a2b46-7f04-4979-8961-3997c0bda8eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d7aa2de0-29a3-4a8f-bf53-20b52ece1c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>07ad6967-c5fd-4e7e-80f3-dad4bb085a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>693b8e71-bbb1-4964-a705-1ce15ba0e2a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>COR 1</value>
      <webElementGuid>23f472af-1fdc-44a8-9486-3363b730fdc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-150-option-6&quot;)</value>
      <webElementGuid>71a0ede1-0a9a-482b-96c7-1e0b6dfeb644</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-150-option-6']</value>
      <webElementGuid>e0755361-073e-43cb-aa0d-4bd9ec8a3852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-150-listbox']/div[7]</value>
      <webElementGuid>06b7a357-7fcd-431c-84ee-7a3e4fe7d119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WHO 3'])[1]/following::div[1]</value>
      <webElementGuid>eb957737-6025-4a61-8625-a7b5e803c22b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='who 2'])[1]/following::div[2]</value>
      <webElementGuid>3ea1a855-5c6f-4eb2-b469-7a80469f9a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COR 3'])[1]/preceding::div[1]</value>
      <webElementGuid>9a6256f5-59fc-4ef3-9c97-34d794e2cbaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COR 6'])[1]/preceding::div[2]</value>
      <webElementGuid>f873f633-2faa-4a04-bd4c-5a9fa4bd522c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='COR 1']/parent::*</value>
      <webElementGuid>cffff1cf-8ae3-4bff-b148-611a444bfdc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[7]</value>
      <webElementGuid>d56a0a64-3e7e-4be2-ae51-81dc3648483a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-150-option-6' and (text() = 'COR 1' or . = 'COR 1')]</value>
      <webElementGuid>08d14b24-a6bc-4fd7-94f3-2b06ad456fab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
