<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>slc_rateCode</name>
   <tag></tag>
   <elementGuidId>82a28596-3df2-40c2-84fa-08f41ce4a877</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-145-placeholder']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Select Rate Code' or . = 'Select Rate Code')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-145-placeholder</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Select Rate Code&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>086086f2-16b1-4fad-a48b-4c0aece4dc33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Select2__placeholder css-1jqq78o-placeholder</value>
      <webElementGuid>f715bca0-6a48-471f-8885-c1531ff2f422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-145-placeholder</value>
      <webElementGuid>8a2c4d9c-af59-41f3-94f6-e2dca90fc572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Rate Code</value>
      <webElementGuid>5fe9d173-50ef-4a40-ba4a-c857a11d05c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-145-placeholder&quot;)</value>
      <webElementGuid>b213afd1-cc2b-41d2-8322-56c5752b7baf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-145-placeholder']</value>
      <webElementGuid>d86222e9-101f-4162-967c-722dd230d3cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='choices-multiple-default']/div/div/div</value>
      <webElementGuid>42ed1e6e-effa-4728-9029-5132f4387512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::div[5]</value>
      <webElementGuid>730023b9-eb7a-4477-94e1-0ff1372af70c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[2]/following::div[5]</value>
      <webElementGuid>6f7621cb-716d-4891-b29b-87ddc398d868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tra 3'])[1]/preceding::div[5]</value>
      <webElementGuid>0cbd975b-4449-4b0a-a9b2-a1527f822afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='travel agent bf 50k'])[1]/preceding::div[6]</value>
      <webElementGuid>2dbb3f5f-ad66-4906-b5af-8539e78597f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select Rate Code']/parent::*</value>
      <webElementGuid>136d58b5-5243-4240-957b-2355bd50760c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div/div/div</value>
      <webElementGuid>727058cf-d1ce-4033-ad32-71fc2415add9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-145-placeholder' and (text() = 'Select Rate Code' or . = 'Select Rate Code')]</value>
      <webElementGuid>1f1785c5-39c6-4b88-823b-c6878d705b43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
