<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_newFIT</name>
   <tag></tag>
   <elementGuidId>483880cc-3b15-43c4-bf52-2df162776694</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[2]/div/div/div[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.w-\[50px\]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bad4dab1-6d9f-46f2-b955-e7bf62857308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://rndhms.dipstrategy.co.id/theme/cms/images/reservation/icon/New_Reservation.svg</value>
      <webElementGuid>f1545448-9ba2-4a0e-9b73-c21a7b26e313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-[50px]</value>
      <webElementGuid>092d16f2-4574-4dd5-9a7e-3eb86ce7590e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;w-full&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;content !mt-[70px] !mb-[10px]  pr-2  pb-16&quot;]/div[@class=&quot;rounded-t-lg p-4&quot;]/div[@class=&quot;mt-2 min-w-full table-auto&quot;]/div[@class=&quot;flex gap-4 auto-cols-max overflow-x-auto min-w-full&quot;]/div[@class=&quot;cursor-pointer&quot;]/div[@class=&quot;flex justify-center w-[60px]&quot;]/img[@class=&quot;w-[50px]&quot;]</value>
      <webElementGuid>176de448-f766-45b7-8c14-10764b4ce5d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div/div/div[2]/div/div/img</value>
      <webElementGuid>5857325d-5852-4be8-8e52-680d51036c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://rndhms.dipstrategy.co.id/theme/cms/images/reservation/icon/New_Reservation.svg')]</value>
      <webElementGuid>c2862e6a-5a89-457f-ad97-814691249b85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/img</value>
      <webElementGuid>b0d2e4b1-dcf9-4fc0-839b-78980a1e89d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://rndhms.dipstrategy.co.id/theme/cms/images/reservation/icon/New_Reservation.svg']</value>
      <webElementGuid>d2430b4a-5232-4a21-b3a0-0006a7f3aded</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
