<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>uploadFile</name>
   <tag></tag>
   <elementGuidId>ff658e42-d484-4a22-857c-174b4aa6f61d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.w-full.border-dashed.border.py-1.px-2.flex.gap-2.items-center</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[2]/div/div[2]/div[3]/table/tbody/tr/td[2]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Upload File&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>52cc6a50-0774-43f9-8409-5233a49b7357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full border-dashed border  py-1 px-2 flex gap-2 items-center</value>
      <webElementGuid>9cc1072c-78f1-4e26-be8c-be3f81b28d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload File</value>
      <webElementGuid>889f8ac0-1e1a-49fa-bc68-853ed982f98e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;w-full&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;content !mt-[70px] !mb-[10px]  pr-2  pb-16&quot;]/div[@class=&quot;rounded-t-lg p-4&quot;]/div[@class=&quot;mt-2 min-w-full table-auto&quot;]/div[@class=&quot;w-full overflow-auto min-h-screen&quot;]/table[@class=&quot;shadow-lg table-auto m-2 min-w-full&quot;]/tbody[@class=&quot;w-full&quot;]/tr[@class=&quot;focus:!bg-[#d4e4fc] hover:!bg-[#d4e4fc]&quot;]/td[@class=&quot;bg-gray-300 p-2&quot;]/div[@class=&quot;min-w-[70px] flex flex-col gap-1&quot;]/div[@class=&quot;w-full py-1&quot;]/div[@class=&quot;flex flex-col items-center justify-center border-[#949eb7] border-dashed border rounded-md min-h-[30px]&quot;]/div[@class=&quot;w-full border-dashed border  py-1 px-2 flex gap-2 items-center&quot;]</value>
      <webElementGuid>2b72dfb3-f17d-4d96-990c-b445a5b08e71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div/div[2]/div[3]/table/tbody/tr/td[2]/div/div/div/div</value>
      <webElementGuid>7a8007ca-76ca-4c7f-a29a-6641b0921d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::div[4]</value>
      <webElementGuid>676ddf61-ceaa-4ae0-b124-7b8c9c4866d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::div[4]</value>
      <webElementGuid>fea60dd2-ac09-49fb-96ab-0ba633b99009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Upload File']/parent::*</value>
      <webElementGuid>8cb30e01-46d6-42e8-aefa-f503cc83ae19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div/div</value>
      <webElementGuid>8a4c9401-6f84-45ca-8c5a-ee74951445bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Upload File' or . = 'Upload File')]</value>
      <webElementGuid>027155cb-949a-4aac-a209-75e893186ea5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
