<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Direct Booking</name>
   <tag></tag>
   <elementGuidId>f4a0ffe7-d85b-4cb9-897a-2176d6d9ce62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-112-option-0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'DIRECT BOOKING' or . = 'DIRECT BOOKING')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-112-option-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;DIRECT BOOKING&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ac1c596c-a1b4-47a6-bee0-b3c6d8be8b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Select2__option Select2__option--is-focused css-d7l1ni-option</value>
      <webElementGuid>68b94f59-e8f9-4121-95ee-736993c92aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>06e30619-5491-4c50-8b04-f573b8f9a8c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-112-option-0</value>
      <webElementGuid>3c54ee69-e215-461e-909b-97738a4367dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>7868665f-0aff-4206-8758-991638464b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>7d5f38a1-86c6-4739-81a8-20a38f766f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>17a926f9-4f7a-4ed9-99e6-ac0a5749020d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DIRECT BOOKING</value>
      <webElementGuid>e5b4932e-3992-4833-9a26-432e6d1de359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-112-option-0&quot;)</value>
      <webElementGuid>ec3cf42d-8e8d-4802-917a-fa48e519686c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-112-option-0']</value>
      <webElementGuid>81442c93-b673-4bdf-ada3-800010c0edb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-112-listbox']/div</value>
      <webElementGuid>c3fa9fc8-4cc5-460b-962b-a140395e9400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Source'])[1]/following::div[6]</value>
      <webElementGuid>704248cb-9b93-491c-9565-c9fba4a48024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::div[10]</value>
      <webElementGuid>bcd7b63b-f4aa-4d7b-ab50-b7dc3ee9c14f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OTHER'])[1]/preceding::div[1]</value>
      <webElementGuid>72fe17a6-0834-438a-93db-8465073b0a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WALK-IN'])[1]/preceding::div[2]</value>
      <webElementGuid>1b10b666-cc0f-4e07-8a64-50528dc502dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DIRECT BOOKING']/parent::*</value>
      <webElementGuid>3e75a39e-605b-4c26-aaa1-c9725f6e1d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div</value>
      <webElementGuid>54668fb9-975e-4cf6-bd9f-fbf8009c49d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-112-option-0' and (text() = 'DIRECT BOOKING' or . = 'DIRECT BOOKING')]</value>
      <webElementGuid>ed730d18-8a36-43b1-8d39-06b50250aacc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
