<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>slc_marketSegment1</name>
   <tag></tag>
   <elementGuidId>766cca70-dafc-42b4-a2f2-cf864cc17fac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-105-placeholder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='choices-multiple-default']/div/div/div)[37]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Market Segment 1&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>89557799-6c69-4e8c-9bb1-19231fb5064d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Select2__placeholder css-1jqq78o-placeholder</value>
      <webElementGuid>885aee45-c46c-497a-ac2e-cfa79322dd27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-105-placeholder</value>
      <webElementGuid>7a47ddd1-f615-45ff-86c4-0f9f123bab9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Market Segment 1</value>
      <webElementGuid>66006789-198f-4f55-9f0f-88a1d0512090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-105-placeholder&quot;)</value>
      <webElementGuid>67219b95-6b79-4150-8e0c-9be24549f196</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-105-placeholder']</value>
      <webElementGuid>d96f047c-1de6-4958-9160-0a38849bde2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='choices-multiple-default']/div/div/div)[37]</value>
      <webElementGuid>f9d4d5bb-6c60-4037-a42b-4ef603158780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::div[4]</value>
      <webElementGuid>fd7162ec-befc-4557-8560-b3bf599068ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/preceding::div[4]</value>
      <webElementGuid>3ff49abf-9192-4d5b-b12e-3f6421606b9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/fieldset[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>ec39766e-c4c8-433e-9417-c9b1baec011c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-105-placeholder' and (text() = 'Market Segment 1' or . = 'Market Segment 1')]</value>
      <webElementGuid>09baa77b-c598-4d0d-9395-4f6c927b2284</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
