<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>slc_staffInCharge</name>
   <tag></tag>
   <elementGuidId>b2b9406d-8a75-4b50-930f-66ee4354eddb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-105-placeholder</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Staff In Charge' or . = 'Staff In Charge')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/div/div[2]/div/div[1]/div/div/div[1]/fieldset[4]/div/div[1]/div/div/div/div[1]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#react-select-105-placeholder</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e7edf68d-34db-42e2-8475-8da899d54e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Select2__placeholder css-1jqq78o-placeholder</value>
      <webElementGuid>bbaf4f2f-1b9a-494d-a6ec-fb36b548f9f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-105-placeholder</value>
      <webElementGuid>32f1dffa-8d73-4d4b-abaf-98c529d5708f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Staff In Charge</value>
      <webElementGuid>3b5ac5ea-cfde-4099-8bcd-13545a09ce2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-105-placeholder&quot;)</value>
      <webElementGuid>1b1207f3-6803-4bf8-9b09-f91d24f2ab77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-105-placeholder']</value>
      <webElementGuid>00bb075c-4144-4c7e-a3f2-7460c08aad40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='choices-multiple-default']/div/div/div)[7]</value>
      <webElementGuid>2fb6143b-e767-4656-8d1a-4f69215e375f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Staff In Charge'])[1]/following::div[4]</value>
      <webElementGuid>8ebb8c58-8a62-4450-a58e-15d08502fa90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Staff'])[1]/following::div[7]</value>
      <webElementGuid>3a899a76-227b-4026-8c16-8bc960ea55cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::div[4]</value>
      <webElementGuid>a255c189-8a8a-4a97-8213-eddc006a1ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/div/div/div/div/div/div/div</value>
      <webElementGuid>c923d335-77f9-4594-8971-e2107e283098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-105-placeholder' and (text() = 'Staff In Charge' or . = 'Staff In Charge')]</value>
      <webElementGuid>50e1eb09-179d-4f87-9553-b36247260de0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
