<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_businessRegistration</name>
   <tag></tag>
   <elementGuidId>879fde97-350d-44a1-96ea-4f5832980785</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;business_regional&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='business_regional']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Business Registration&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa6f26bc-bb92-42a6-a65b-b730eda641ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>business_regional</value>
      <webElementGuid>a24ef1b6-85e0-43b4-8af9-f108646fda9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Business Registration</value>
      <webElementGuid>a61fb75e-8d68-462d-95f1-ad53dbc5d26a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5dd7708c-09f2-4b05-b6e9-72f9c9a3be63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>  border   border-dashed focus:!border-blue focus:border-dashed rounded-md py-1 focus:outline-0 focus:outline-dashed focus:ring-transparent   uppercase </value>
      <webElementGuid>167d096b-30b2-4604-8fa3-70d399f04a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;w-full&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;content !mt-[70px] !mb-[10px]  pr-2  pb-16&quot;]/div[@class=&quot;rounded-t-lg p-4&quot;]/div[@class=&quot;flex flex-col gap-4&quot;]/div[@class=&quot;grid grid-cols-12 h-fit gap-4&quot;]/div[@class=&quot;col-span-12 grid grid-cols-12 h-fit  gap-4&quot;]/div[@class=&quot;col-span-4&quot;]/fieldset[@class=&quot;border&quot;]/div[@class=&quot;grid grid-cols-12 h-fit gap-4 ml-2 mb-4 mt-4 mr-2&quot;]/div[@class=&quot;col-span-6&quot;]/div[@class=&quot;min-w-[70px] flex flex-col gap-1&quot;]/input[@class=&quot;border   border-dashed focus:!border-blue focus:border-dashed rounded-md py-1 focus:outline-0 focus:outline-dashed focus:ring-transparent   uppercase&quot;]</value>
      <webElementGuid>042cef52-18fb-4c47-be23-730180955bae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='business_regional']</value>
      <webElementGuid>b7bdbc45-2c5f-493e-8472-8767a03da210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div/div/div/div/div/fieldset[2]/div/div[3]/div/input</value>
      <webElementGuid>58310d68-d480-49be-be6f-8697753852c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>356a1805-1c25-491d-bf74-305c21789bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'business_regional' and @placeholder = 'Business Registration' and @type = 'text']</value>
      <webElementGuid>f7771ced-c9b6-473e-975e-b8c980f99f62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
