<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_descriptionDocument</name>
   <tag></tag>
   <elementGuidId>7620a4fe-47fc-4903-96a7-2dc6947b9534</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;description&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>125d5c25-452c-4e72-89f5-5947673e8512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>cf117b75-0448-4923-8a23-ddc40058373a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>92169e0c-34e9-4a4e-9968-5c54eaeb316a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>  border   border-dashed focus:!border-blue focus:border-dashed rounded-md py-1 focus:outline-0 focus:outline-dashed focus:ring-transparent   uppercase </value>
      <webElementGuid>7e50784a-82ed-4017-a92a-84cf1ed114b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;w-full&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;content !mt-[70px] !mb-[10px]  pr-2  pb-16&quot;]/div[@class=&quot;rounded-t-lg p-4&quot;]/div[@class=&quot;mt-2 min-w-full table-auto&quot;]/div[@class=&quot;w-full overflow-auto min-h-screen&quot;]/table[@class=&quot;shadow-lg table-auto m-2 min-w-full&quot;]/tbody[@class=&quot;w-full&quot;]/tr[@class=&quot;focus:!bg-[#d4e4fc] hover:!bg-[#d4e4fc]&quot;]/td[@class=&quot;bg-gray-300 p-2&quot;]/div[@class=&quot;min-w-[70px] flex flex-col gap-1&quot;]/input[@class=&quot;border   border-dashed focus:!border-blue focus:border-dashed rounded-md py-1 focus:outline-0 focus:outline-dashed focus:ring-transparent   uppercase&quot;]</value>
      <webElementGuid>e63d6e06-d719-49e1-9534-dab409389d4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='description']</value>
      <webElementGuid>39cd3aa5-abe3-4f0e-93d2-07e6db128fa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div/div[2]/div[3]/table/tbody/tr/td[3]/div/input</value>
      <webElementGuid>9acfa757-e66a-413f-8087-2020e67171c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/input</value>
      <webElementGuid>53a9aed1-2bec-46de-b011-24538507d05e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'description' and @type = 'text']</value>
      <webElementGuid>5a151073-1cee-41fe-bbaa-ca750d07df95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
