<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_website</name>
   <tag></tag>
   <elementGuidId>211ac9ad-62e0-41bf-9bcd-c567e51ac084</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;website&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='website']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Website&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a6a8b861-1f31-4d0c-9b9c-f6027c00e66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>website</value>
      <webElementGuid>ce11abb1-2ca0-4cce-93a4-8a657451242f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Website</value>
      <webElementGuid>2b880bb3-e51b-4d77-ad84-a1d1cd1e8363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>11b612c4-9a04-4d53-b226-533887dfe750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>  border   border-dashed focus:!border-blue focus:border-dashed rounded-md py-1 focus:outline-0 focus:outline-dashed focus:ring-transparent   uppercase </value>
      <webElementGuid>8155cc25-8b77-433a-a845-a55a6c647c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;w-full&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;content !mt-[70px] !mb-[10px]  pr-2  pb-16&quot;]/div[@class=&quot;rounded-t-lg p-4&quot;]/div[@class=&quot;flex flex-col gap-4&quot;]/div[@class=&quot;grid grid-cols-12 h-fit gap-4&quot;]/div[@class=&quot;col-span-12 grid grid-cols-12 h-fit  gap-4&quot;]/div[@class=&quot;col-span-4&quot;]/fieldset[@class=&quot;border&quot;]/div[@class=&quot;grid grid-cols-12 h-fit gap-4 ml-2 mb-4 mt-4 mr-2&quot;]/div[@class=&quot;col-span-6&quot;]/div[@class=&quot;min-w-[70px] flex flex-col gap-1&quot;]/input[@class=&quot;border   border-dashed focus:!border-blue focus:border-dashed rounded-md py-1 focus:outline-0 focus:outline-dashed focus:ring-transparent   uppercase&quot;]</value>
      <webElementGuid>e6d580b2-f02b-4fa9-b5a0-3bcbb70d8d05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='website']</value>
      <webElementGuid>7a1f7eab-7f22-4913-a4f8-22fbb6b0b67a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div/div/div/div/div/fieldset[3]/div/div[3]/div/input</value>
      <webElementGuid>69d5f4a5-db9d-4100-8e9c-7e85e2852c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div[3]/div/input</value>
      <webElementGuid>d1a068e8-b2d1-4d4e-bd51-0dee20cb627e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'website' and @placeholder = 'Website' and @type = 'text']</value>
      <webElementGuid>cd2a1a51-402e-46f0-92d1-ea272e859159</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
