<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>uploadFile</name>
   <tag></tag>
   <elementGuidId>b11c6de4-d8a1-432f-a36e-f0f93bfd120c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/div/div[2]/div/div[2]/div[3]/table/tbody/tr[1]/td[2]/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.w-full.border-dashed.border.py-1.px-2.flex.gap-2.items-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Upload File&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>84256ee4-7ca5-4ecc-84f2-292f2d26ad07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full border-dashed border  py-1 px-2 flex gap-2 items-center</value>
      <webElementGuid>998d17b4-1215-43d1-9279-117eaa35f62d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload File</value>
      <webElementGuid>6f781bee-202d-476c-8408-4a5765ed6197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;w-full&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;content !mt-[70px] !mb-[10px]  pr-2  pb-16&quot;]/div[@class=&quot;rounded-t-lg p-4&quot;]/div[@class=&quot;mt-2 min-w-full table-auto&quot;]/div[@class=&quot;w-full overflow-auto min-h-screen&quot;]/table[@class=&quot;shadow-lg table-auto m-2 min-w-full&quot;]/tbody[@class=&quot;w-full&quot;]/tr[@class=&quot;focus:!bg-[#d4e4fc] hover:!bg-[#d4e4fc]&quot;]/td[@class=&quot;bg-gray-300 p-2&quot;]/div[@class=&quot;min-w-[70px] flex flex-col gap-1&quot;]/div[@class=&quot;w-full py-1&quot;]/div[@class=&quot;flex flex-col items-center justify-center border-[#949eb7] border-dashed border rounded-md min-h-[30px]&quot;]/div[@class=&quot;w-full border-dashed border  py-1 px-2 flex gap-2 items-center&quot;]</value>
      <webElementGuid>e10c2864-0c3c-4355-b831-76baa4348da3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div/div[2]/div[3]/table/tbody/tr/td[2]/div/div/div/div</value>
      <webElementGuid>3cbc21d1-426d-4054-98ef-09ab51285774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::div[4]</value>
      <webElementGuid>dc83d6e3-23c9-464f-906b-bc35eed00774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::div[4]</value>
      <webElementGuid>199745c6-e2e2-4fce-bd32-c458340da1f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='burnice.jpg'])[1]/preceding::div[3]</value>
      <webElementGuid>90fa2657-aa1e-46c7-b609-6ca45081d1f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pas foto'])[1]/preceding::div[3]</value>
      <webElementGuid>a6b30bee-d3c7-447b-be94-aaf8ab052831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Upload File']/parent::*</value>
      <webElementGuid>c9c939e2-5035-450c-ac5a-419a77fd99e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div/div</value>
      <webElementGuid>f47724c3-e87f-462d-9aba-551f3bfe2d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Upload File' or . = 'Upload File')]</value>
      <webElementGuid>7ecb65c2-308f-4ef2-a2ec-2aa5c6478198</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
