<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>KTP</name>
   <tag></tag>
   <elementGuidId>8b99086d-f2dc-4043-a97e-4f4b7773f9f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id = 'react-select-46-option-0' and (text() = 'KTP' or . = 'KTP')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'KTP' or . = 'KTP')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>471e5d17-b97c-4ad3-8e19-34a62e869548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Select2__option Select2__option--is-focused css-d7l1ni-option</value>
      <webElementGuid>3ab312a1-4592-4a75-a625-2e0de84c5590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cecd9c51-e4ad-47c3-8425-57f44109a5a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-46-option-0</value>
      <webElementGuid>d89401ce-9896-4e27-be04-42cf37269506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>763acb44-2e7d-46ec-8aeb-be928ee27ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>0340c1d8-16cf-47de-9300-f502ce5bb335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KTP</value>
      <webElementGuid>d030ce30-3dd6-488b-8a25-c86d4b79c39d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@id=&quot;choices-multiple-default&quot;]/div[@class=&quot;Select2__menu css-1hbks0g-menu&quot;]/div[@id=&quot;react-select-46-listbox&quot;]/div[@id=&quot;react-select-46-option-0&quot;]</value>
      <webElementGuid>71f48229-df57-4adf-b0df-e2a8a1db0b07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-46-option-0' and (text() = 'KTP' or . = 'KTP')]</value>
      <webElementGuid>290f49f1-e026-4b45-a3ec-4259eb8594f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
