<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MRS</name>
   <tag></tag>
   <elementGuidId>a65c37a4-c046-4f84-bef8-43d7b6d2f4c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'MRS' or . = 'MRS')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id = 'react-select-44-option-0' and (text() = 'MR' or . = 'MR')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>84365c8b-ae64-4fc2-959b-9d59d9fb899f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Select2__option Select2__option--is-focused css-d7l1ni-option</value>
      <webElementGuid>f267115c-e9b5-4c79-afe1-da1d3ca03450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6b89c5ee-f953-43df-a169-15878173b379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-44-option-0</value>
      <webElementGuid>0e210dbc-d245-4e95-9be7-c061a03ad927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f87d2150-146b-4f33-9761-8e801f87cde9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>56385206-c32a-4207-9fbc-2e8dc83f13c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MRS</value>
      <webElementGuid>627a0623-79d4-4c79-a5b2-458287823ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@id=&quot;choices-multiple-default&quot;]/div[@class=&quot;Select2__menu css-1hbks0g-menu&quot;]/div[@id=&quot;react-select-44-listbox&quot;]/div[@id=&quot;react-select-44-option-0&quot;]</value>
      <webElementGuid>7249c1e7-94e4-4cd3-82b2-3d0863c2f4a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-44-option-0' and (text() = 'MR' or . = 'MR')]</value>
      <webElementGuid>b3d3b1d0-6ea5-4ccd-b426-fcc7c2eb2f56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
