<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NRIC</name>
   <tag></tag>
   <elementGuidId>b7c16023-e5c5-4396-97d0-5404e70aafd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/div[@id=&quot;choices-multiple-default&quot;]/div[@class=&quot;Select2__control Select2__control--is-focused css-t3ipsp-control&quot;]/div[@class=&quot;Select2__value-container css-ovps6s&quot;]/div[@class=&quot;Select2__input-container css-19bb58m&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/div/div[2]/div/div[2]/div/div/div[1]/fieldset/div[2]/div[7]/div/div/div/div[1]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d687f65d-cc8a-423d-8cee-71ef62ca6156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Select2__input-container css-19bb58m</value>
      <webElementGuid>4885c32f-638c-42f7-a42f-9e26ba2857dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@id=&quot;choices-multiple-default&quot;]/div[@class=&quot;Select2__control Select2__control--is-focused css-t3ipsp-control&quot;]/div[@class=&quot;Select2__value-container css-ovps6s&quot;]/div[@class=&quot;Select2__input-container css-19bb58m&quot;]</value>
      <webElementGuid>b16d894e-720a-4d2e-acfa-2c6266c12b85</webElementGuid>
   </webElementProperties>
</WebElementEntity>
