<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Paspor</name>
   <tag></tag>
   <elementGuidId>ca2548e9-b423-4019-8222-138d7c42e0af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Paspor' or . = 'Paspor')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id = 'react-select-46-option-0' and (text() = 'KTP' or . = 'KTP')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f852a45e-845e-4cde-badc-47c7c6aaaf2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Select2__option Select2__option--is-focused css-d7l1ni-option</value>
      <webElementGuid>34d93477-095b-47a8-abf9-d53b79eefdd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0632603d-7126-438c-b54e-cd3cd6f379d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-46-option-0</value>
      <webElementGuid>0de8f364-3362-40d8-b17a-5a0f1692e266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>77f49883-c09a-4054-af96-682450f2b850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d722ac88-5669-4f75-937f-54711ce37d8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Paspor</value>
      <webElementGuid>6a27a369-a930-4f00-8cf0-27f04aa902cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@id=&quot;choices-multiple-default&quot;]/div[@class=&quot;Select2__menu css-1hbks0g-menu&quot;]/div[@id=&quot;react-select-46-listbox&quot;]/div[@id=&quot;react-select-46-option-0&quot;]</value>
      <webElementGuid>73add9a9-5c30-420c-9c35-ba0a30aa72c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-46-option-0' and (text() = 'KTP' or . = 'KTP')]</value>
      <webElementGuid>f21e4a71-04d2-4727-8629-f352d20e9a06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
