<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ta_description</name>
   <tag></tag>
   <elementGuidId>19cadde5-fe00-4fab-b64f-49e4071affce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;description&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Description&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e6652130-f86f-4d6f-b1b8-dd3142cb3286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>4cb6462d-3a95-44d3-bb89-3d1a7cebc299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>64c96069-2d2e-43dc-bad3-52a74b8b72e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border uppercase   focus:!border-blue border-dashed focus:border-dashed rounded py-1 px-3 focus:outline-0 border-[#949eb7]focus:outline-dashed rounded-md focus:ring-transparent </value>
      <webElementGuid>ddf61d35-bd50-4b1b-b0d9-5a5a9172240f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;w-full&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;content !mt-[70px] !mb-[10px]  pr-2  pb-16&quot;]/div[@class=&quot;rounded-t-lg p-4&quot;]/div[@class=&quot;flex flex-col gap-4&quot;]/div[@class=&quot;grid grid-cols-12 h-fit gap-4&quot;]/div[@class=&quot;col-span-12 sm:grid grid-cols-12 h-fit  gap-2&quot;]/div[@class=&quot;col-span-12&quot;]/fieldset[@class=&quot;border&quot;]/div[@class=&quot;sm:grid grid-cols-12 h-fit gap-4 ml-2 mb-4 mt-4 mr-2&quot;]/div[@class=&quot;col-span-6&quot;]/div[@class=&quot;flex flex-col gap-1&quot;]/textarea[@class=&quot;border uppercase   focus:!border-blue border-dashed focus:border-dashed rounded py-1 px-3 focus:outline-0 border-[#949eb7]focus:outline-dashed rounded-md focus:ring-transparent&quot;]</value>
      <webElementGuid>3966d09c-f786-4b92-abff-629aa9e76476</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='description']</value>
      <webElementGuid>71b6e150-9cf5-4dd0-9d12-633fdd6d0a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div/div/div[2]/div/div/fieldset/div/div[3]/div/textarea</value>
      <webElementGuid>df091246-1bf9-413d-8caa-48cf8edca547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>61a1460a-3e12-4ef2-9fc4-8f9677d6609d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Description' and @name = 'description']</value>
      <webElementGuid>4b5534b3-90a1-4035-8431-cfe53fef6b2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
