<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>slc_postCodeExtraBed</name>
   <tag></tag>
   <elementGuidId>1a3b0c59-49a7-434a-b91f-f693bcbf4ec7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-17-placeholder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-17-placeholder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Select Post Code Extra Bed&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f2735803-46e1-475b-8e9e-74cb03ca5529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Select2__placeholder css-1jqq78o-placeholder</value>
      <webElementGuid>600ec288-d90e-41c1-a6c4-d4787e0ed912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-17-placeholder</value>
      <webElementGuid>12cd8542-d4c1-4b71-a8c3-19c618960ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Post Code Extra Bed</value>
      <webElementGuid>09bff7f7-2122-4e7a-98f9-a4020866d46e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-17-placeholder&quot;)</value>
      <webElementGuid>b98e9ec4-bc30-467e-8f72-3c9f1044ce65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-17-placeholder']</value>
      <webElementGuid>b57ac1fa-e985-4973-8b9d-a79947fbde59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='choices-multiple-default']/div/div/div)[4]</value>
      <webElementGuid>2263e568-79a3-4be3-9f45-f2c56ee3e6dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ROOM REVENUE'])[1]/following::div[8]</value>
      <webElementGuid>76c8dd98-fdc6-47bd-a9be-26df5035bd4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::div[20]</value>
      <webElementGuid>e1ac36b5-5911-49cc-ab0b-6956820a8767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ROOM REVENUE'])[2]/preceding::div[4]</value>
      <webElementGuid>db1ccde0-b33d-4e57-8288-d3a64b6676e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UPGRADE ROOM'])[1]/preceding::div[5]</value>
      <webElementGuid>c76a6b80-c871-43a3-9a9a-431c85cc8462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select Post Code Extra Bed']/parent::*</value>
      <webElementGuid>82ecf89c-f9ee-4eb7-a240-03e1e96743c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/div/div/div/div/div</value>
      <webElementGuid>3da1ac5a-ed6d-40f8-9d0e-25efc083565b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-17-placeholder' and (text() = 'Select Post Code Extra Bed' or . = 'Select Post Code Extra Bed')]</value>
      <webElementGuid>5c4af546-d166-4331-93d3-0a51239360e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
