<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_companyName</name>
   <tag></tag>
   <elementGuidId>b616942a-a9e4-400d-8c30-ef323b6ae3f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Company&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f8941681-d52f-44bc-85d4-cf275617a79d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>b796d0ca-d174-4791-8717-cf32e0301965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Company</value>
      <webElementGuid>03fcb8ee-4692-4acc-ba3f-99d84efd5478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e878bfca-9a1c-4114-bf89-cb86efda724a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>  border   border-dashed focus:!border-blue focus:border-dashed rounded-md py-1 focus:outline-0 focus:outline-dashed focus:ring-transparent   uppercase </value>
      <webElementGuid>fccaf9e8-169d-409f-9d50-5ae0ac8a4e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;w-full&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;content !mt-[70px] !mb-[10px]  pr-2  pb-16&quot;]/div[@class=&quot;rounded-t-lg p-4&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;absolute w-full z-20&quot;]/div[@class=&quot;flex   items-center justify-center z-20&quot;]/div[@class=&quot;bg-white p-4  rounded-lg shadow-lg&quot;]/div[@class=&quot;order-3 w-full flex mb-2 mt-2&quot;]/fieldset[@class=&quot;border w-full&quot;]/div[@class=&quot;sm:grid grid-cols-4 gap-2 mt-[20px]  mb-2 justify-end m-2&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;min-w-[70px] flex flex-col gap-1&quot;]/input[@class=&quot;border   border-dashed focus:!border-blue focus:border-dashed rounded-md py-1 focus:outline-0 focus:outline-dashed focus:ring-transparent   uppercase&quot;]</value>
      <webElementGuid>5549e405-b7f8-4bf5-9acf-158ab96e44a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='name']</value>
      <webElementGuid>3d3e6c87-c78f-4059-bd87-109ea1c9bd51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div/div[2]/div/div/div/div[3]/fieldset/div/div[6]/div/input</value>
      <webElementGuid>2f417d2a-86c1-4099-b2d7-5b4d45684919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>a3885d33-1382-4ef0-ae0f-f64521cb467c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'name' and @placeholder = 'Company' and @type = 'text']</value>
      <webElementGuid>951e7de7-fc56-4673-9bdf-9fb33520bd22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
