<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_edit</name>
   <tag></tag>
   <elementGuidId>d40ddc08-c105-4364-a23d-bc64d749b44f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[2]/div/div/div[4]/table/tbody/tr/td/div/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;CA000008 Corporate AMARTHA normal&quot;i] >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>33ffed75-4e6c-4aae-8f05-e97925e9e48c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/apps/edit.png</value>
      <webElementGuid>da813ce3-9eb8-4124-930e-130e7671e975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-[21px]</value>
      <webElementGuid>e511f7bd-dd53-4263-b87c-0c770cdd9d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;w-full&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;content !mt-[70px] !mb-[10px]  pr-2  pb-16&quot;]/div[@class=&quot;rounded-t-lg p-4&quot;]/div[@class=&quot;mt-2 min-w-full table-auto&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;shadow-lg table-auto m-2 min-w-full&quot;]/tbody[@class=&quot;w-full&quot;]/tr[@class=&quot;focus:!bg-[#ead6b4] hover:!bg-[#ead6b4]&quot;]/td[@class=&quot;bg-gray-300 p-2 focus:!bg-[#ead6b4] hover:!bg-[#ead6b4] border-r-2 !border-r-[#000000]&quot;]/div[@class=&quot;flex gap-2&quot;]/button[@class=&quot;w-[21px]&quot;]/img[@class=&quot;w-[21px]&quot;]</value>
      <webElementGuid>9a57878e-ad89-4e84-8002-50db5fd3e3b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div/div/div[4]/table/tbody/tr/td/div/button/img</value>
      <webElementGuid>2c40c866-b151-4e8f-b6cb-ca51bdb2bec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>57c7aeac-f15e-4c74-a3c6-0e208e4e5a83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/images/apps/edit.png']</value>
      <webElementGuid>da550660-0555-4e92-966f-8d91f27affda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
