<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>newFIT</name>
   <tag></tag>
   <elementGuidId>d331e02b-52b7-4332-ae84-6cb62ca1c041</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[2]/div/div/div[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.w-\[50px\]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>18b672fa-2571-4f3c-9f75-6d84eefcebd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://rndhms.dipstrategy.co.id/theme/cms/images/reservation/icon/New_Reservation.svg</value>
      <webElementGuid>d56d3373-3c2c-4a87-ae17-f5c2c7e2e21c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-[50px]</value>
      <webElementGuid>3f81184d-f944-462f-8e7c-cf14961b91dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;w-full&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;content !mt-[70px] !mb-[10px]  pr-2  pb-16&quot;]/div[@class=&quot;rounded-t-lg p-4&quot;]/div[@class=&quot;mt-2 min-w-full table-auto&quot;]/div[@class=&quot;flex gap-4 auto-cols-max overflow-x-auto min-w-full&quot;]/div[@class=&quot;cursor-pointer&quot;]/div[@class=&quot;flex justify-center w-[60px]&quot;]/img[@class=&quot;w-[50px]&quot;]</value>
      <webElementGuid>225cfba4-3766-4e70-833c-e76e3fe637f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div/div/div[2]/div/div/img</value>
      <webElementGuid>484ec574-fe10-488e-a720-dbd3d9071bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://rndhms.dipstrategy.co.id/theme/cms/images/reservation/icon/New_Reservation.svg')]</value>
      <webElementGuid>72377dfe-ac83-4902-b9fc-24db4d981f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/img</value>
      <webElementGuid>0087e584-dc8d-4aa5-8ecd-97be051718f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://rndhms.dipstrategy.co.id/theme/cms/images/reservation/icon/New_Reservation.svg']</value>
      <webElementGuid>76c80ed2-da76-4cb6-9878-46c9c5b95c10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
