<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Gender_edit</name>
   <tag></tag>
   <elementGuidId>49e28e9f-8d05-4d21-869d-7e16dcc9009b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-87-placeholder</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Gender' or . = 'Gender')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/div/div[2]/div/div[2]/div/div/div[1]/fieldset/div[2]/div[12]/div/div/div/div[1]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8262395d-7431-4fa7-9aef-48d6e45239a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Select2__placeholder css-1jqq78o-placeholder</value>
      <webElementGuid>81421b55-2d4f-418a-8ed2-81fb19b57d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-87-placeholder</value>
      <webElementGuid>4832e94a-61cb-49d4-bd3a-58e73f23ca4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gender</value>
      <webElementGuid>a2ce94de-567f-46ed-9551-e7f095b999e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-87-placeholder&quot;)</value>
      <webElementGuid>57098724-7a05-4e9d-b440-40fcfbc778dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-87-placeholder']</value>
      <webElementGuid>ec03b0e5-4ec6-4ae6-8859-ec178c3bdb3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='choices-multiple-default']/div/div/div)[10]</value>
      <webElementGuid>e5cb4e86-9baf-4626-8b4d-8741414887d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='option , selected.'])[1]/following::div[3]</value>
      <webElementGuid>8d9955f3-cd86-4a65-8195-3aca26c61ec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/following::div[4]</value>
      <webElementGuid>da897bfa-cdbe-4f8d-8a06-f20308773906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Male'])[1]/preceding::div[4]</value>
      <webElementGuid>ffcd4125-b391-4480-99df-9388c1d33578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Female'])[1]/preceding::div[5]</value>
      <webElementGuid>877de4e6-840f-453a-bfa5-f703174ac0dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div/div/div</value>
      <webElementGuid>6341a645-001c-4c14-a7e8-b64ee380d301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-87-placeholder' and (text() = 'Gender' or . = 'Gender')]</value>
      <webElementGuid>2b0ae045-a43f-4c4c-8ed6-4f32bc730bbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
