<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Kota Administrasi Jakarta Barat</name>
   <tag></tag>
   <elementGuidId>c2664d63-06c8-4fb5-bcc3-e426b701dd8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-76-option-542</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Kota Administrasi Jakarta Barat' or . = 'Kota Administrasi Jakarta Barat')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-76-option-542']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>588bbe17-6bd3-4825-a630-662e77a62759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Select2__option Select2__option--is-focused css-d7l1ni-option</value>
      <webElementGuid>30d485cd-dee8-4ac8-9eca-94a34ea85fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>809cea54-813c-4627-af7a-7816cb2da7e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-76-option-542</value>
      <webElementGuid>1495d6f0-033b-4854-982f-c6a23eb6c2c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>22d645b4-ce59-4241-9687-de65883846b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>8549bc42-08b4-483d-a6d5-4494b5a10998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b8694043-f982-425f-8628-29928f0d7055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kota Administrasi Jakarta Barat</value>
      <webElementGuid>567730e2-66b4-4aae-ae65-121d8aacca22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-76-option-542&quot;)</value>
      <webElementGuid>80f853ab-a2ab-4818-b2a3-fcb973cb3aa2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-76-option-542']</value>
      <webElementGuid>4e8048a6-8e7c-42cb-b4f0-ffac12299033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-76-listbox']/div</value>
      <webElementGuid>7cbbf0f6-e2be-4d98-b0d6-723ea23cf57e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/following::div[9]</value>
      <webElementGuid>84067073-61a5-4845-b906-db5bcd988fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia'])[1]/following::div[14]</value>
      <webElementGuid>54af7acd-16a4-4b53-810e-006ea2252cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kota Administrasi Jakarta Pusat'])[1]/preceding::div[1]</value>
      <webElementGuid>20dfc7eb-6754-4d0a-8f80-309c4fed313a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kota Administrasi Jakarta Selatan'])[1]/preceding::div[2]</value>
      <webElementGuid>edb35f0d-b5cb-46a7-b3b4-bed86f15f016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kota Administrasi Jakarta Barat']/parent::*</value>
      <webElementGuid>eea393af-e5b7-45fd-b8d0-4825309f684d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[23]/div/div/div[2]/div/div</value>
      <webElementGuid>da48676c-9c61-4d7c-be2b-e648699c7cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-76-option-542' and (text() = 'Kota Administrasi Jakarta Barat' or . = 'Kota Administrasi Jakarta Barat')]</value>
      <webElementGuid>a2a52ace-c3a2-41b9-bb9e-dff4c50c839b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
