<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toggle_enable</name>
   <tag></tag>
   <elementGuidId>eb7c864e-6d53-4098-9ce3-53c1a141ec94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.label-primary.mt-2</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;__next&quot;)/div[@class=&quot;w-full&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;content !mt-[70px] !mb-[10px]  pr-2  pb-16&quot;]/div[@class=&quot;rounded-t-lg p-4&quot;]/div[@class=&quot;flex flex-col gap-4&quot;]/div[@class=&quot;grid grid-cols-12 h-fit gap-4&quot;]/div[@class=&quot;col-span-12 sm:grid grid-cols-12 h-fit  gap-2&quot;]/div[@class=&quot;col-span-12&quot;]/fieldset[@class=&quot;border&quot;]/div[@class=&quot;sm:grid grid-cols-12 h-fit gap-4 ml-2 mb-4 mt-4 mr-2&quot;]/div[@class=&quot;col-span-3&quot;]/div[1]/div[@class=&quot;custom-toggle-switch toggle-sm flex items-center flex&quot;]/label[@class=&quot;label-primary mt-2&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/div/div[2]/div/div[1]/div[2]/div/div/fieldset[1]/div/div[1]/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.label-primary</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>2a43e55f-a18b-45c0-8651-5f6857b5403a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>statusid</value>
      <webElementGuid>a8c34eb9-77e8-4452-b241-ee20cab7e2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label-primary mt-2</value>
      <webElementGuid>ecd1b0e9-6f14-4017-b633-a4843e2c7225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;w-full&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;content !mt-[70px] !mb-[10px]  pr-2  pb-16&quot;]/div[@class=&quot;rounded-t-lg p-4&quot;]/div[@class=&quot;flex flex-col gap-4&quot;]/div[@class=&quot;grid grid-cols-12 h-fit gap-4&quot;]/div[@class=&quot;col-span-12 sm:grid grid-cols-12 h-fit  gap-2&quot;]/div[@class=&quot;col-span-12&quot;]/fieldset[@class=&quot;border&quot;]/div[@class=&quot;sm:grid grid-cols-12 h-fit gap-4 ml-2 mb-4 mt-4 mr-2&quot;]/div[@class=&quot;col-span-3&quot;]/div[1]/div[@class=&quot;custom-toggle-switch toggle-sm flex items-center flex&quot;]/label[@class=&quot;label-primary mt-2&quot;]</value>
      <webElementGuid>04477955-2f94-43ec-8106-df475cbac900</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div/div/div[2]/div/div/fieldset/div/div/div/div/label</value>
      <webElementGuid>a851c7df-34d0-45b2-bd13-c8de77ae4d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>01be4820-9cb2-4447-a11b-570d4a85b07a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
